### PR TITLE
Readme udpate - add contribution section, add twigyard link, see #3

### PR DESCRIPTION
**Pull request by adinafxv**

### CODE REVIEW

**Review by mbohal — APPROVED** [review]

**Comment by adamkudrna** [comment]
I know I'm late but how about this one:

> This site is built on TwigYard, a PHP library to host multiple websites written in the Twig templating language.

I've just added this to https://github.com/Frontendisti-cz/frontendisti.cz/blob/master/README.md.

What does @mbohal think?

**Comment by mbohal** [comment]
I think I like Adam's version slightly more, but I'm fine with either one.

**Review by adamkudrna — CHANGES_REQUESTED** [review]
It's actually the tagline of TwigYard repository here on GitHub, I forgot about it.

OK, @adinafoxova, could you please change it to my version? Sorry for complication!

**Comment by adamkudrna** [comment]
Here in Markdown:

```
This site is built on [TwigYard](https://github.com/twigyard/twigyard), a PHP library to host multiple websites
written in the Twig templating language.
```

**Review by adamkudrna — APPROVED** [review]

**Pull request merged**
